FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["About_me.csproj", "./"]
RUN dotnet restore "About_me.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "About_me.csproj" -c Release -o /app/build
RUN dotnet publish "About_me.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "About_me.dll"]